project_id      = "data-platform-490117"
project_number  = "926377652927"
region          = "europe-west2"
instance_id     = "dbp-primary"
backup_bucket   = "dbp-backups-data-platform-490117"
cloud_run_image = "europe-west2-docker.pkg.dev/data-platform-490117/dbp-control-plane/dbp-control-plane:dev"
github_repo     = "ylanning/db-platform"
